name: issues listiner

on: [issues]

jobs:
  details:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: print issue info
        run: echo "${{ toJson(github.event.issue) }}"
