name: qa tests

on: push

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install deps
        run: npm ci
      - name: install browsers
        run: npx playwright install --with-deps
      - name: run pw tests
        run: npx playwright test