name: Reusable deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        description: name of the artifact
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
    outputs:
      result:
        description: result of the deployment
        value: ${{ jobs.deploy.outputs.outcome}}

jobs:
  deploy:
    outputs:
      outcome: ${{steps.deploy.outputs.result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name }}
      - name: output contents
        run: ls
      - name: info
        run: echo "deploying..."
      - name: set result
        id: deploy
        run: echo "result=deployed" >> $GITHUB_OUTPUT
